CREATE FUNCTION GET_GENERATED_QUESTION(@IDTest INT)
RETURNS TABLE  
AS  
RETURN   
(
	WITH CTE_QUESTIONS
	AS
	(
		SELECT QST.ID AS IDQUESTION
		, QST.STATEMENT
		, QST.MEDIA
		, QST.POINTS
		, THE.ID AS IDTHEME
		, THE.LABEL
		, ROW_NUMBER() OVER (PARTITION BY THE.ID
			ORDER BY NEWID()) NBQUESTIONS
		FROM QUESTION QST
			INNER JOIN THEME THE ON THE.ID = QST.IDTHEME
	)
	SELECT CTQ.IDQUESTION
	, CTQ.STATEMENT
	, CTQ.MEDIA
	, CTQ.POINTS
	, CTQ.IDTHEME
	, CTQ.LABEL
	FROM TEST TST
		INNER JOIN TEST_SECTION SCT ON SCT.IDTEST = TST.ID
		INNER JOIN CTE_QUESTIONS CTQ ON CTQ.IDTHEME = SCT.IDTHEME
	WHERE TST.ID = 1
	AND CTQ.NBQUESTIONS <= SCT.NBQUESTIONTODRAW
);  